url: "https://indiannarrative.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "The Indian Narrative" # the name of your site, e.g. ACME Corp.
description: "A centralized platform for Indians to take control of their narrative, knowledge, and perspective."